#!/bin/sh

# The post commit script is roughly the inverse of the pre-commit script.
# It restores any removed raw cells and converts markdown cells back to
# nbRaw where applicable. In the future, it may commit the changes to a
# a development branch to allow master to have a clean head.

enabled="$(git config --bool hooks.post-commit.enabled)"
changed=( `git diff --name-only HEAD HEAD~1 | grep -E "[0-9]+.+\.ipynb"` )
if [ "$enabled" != 'false' -a "$changed" ]
then
	echo "Post commit start..(${changed[*]})"
	for file in "${changed[@]}"; do
		echo "Raw Convert: $file"
		python hooks/gitexport.py -i -t raw "$file"
	done || exit 1
	
	echo "Post commit finished, restoring raw cells (${changed[*]})"
	# git stash push -p -- "${changed[*]}"
fi
exit 0