#!/bin/sh

# This script takes staged .ipynb files and prepares each for submission
# to GitHub. It converts raw cells to markdown where applicable and
# adds the modifications back into the commit.

changed=( `git diff --cached --name-only | grep -E "[0-9]+.+\.ipynb"` )
if [ "$changed" ]
then
	echo "Pre-commit start...(${#changed[@]} files: ${changed[@]})"
	for file in "${changed[@]}"; do
		echo "Markdown Convert: $file"
		python hooks/gitexport.py -i -t markdown "$file"
	done || exit 1 # exit if for-loop errors
	
	git add "${changed[*]}"
	echo "Pre-commit end"
fi
exit 0
